#' @title Inserts plant species into the terrain matrix.
#' @description Simulation of plant species placed on the terrain matrix
#'    built in 'terrain.r'. Where there is terrain, the plant species
#'    initially survive, then reproduce, and eventually compete with each
#'    other.
#' @param repduc the probability that the corresponding plant species
#'    reproduces.
#' @param survive the probability that the corresponding plant species
#'    survives.
#' @param names argument that links a logical value to its corresponding
#'    numerical value for survive and reproduction.
#' @return initiate.plants objects
#' @importFrom stats rnorm
#' @importFrom stats runif setNames
#' @examples
#'    plants<-run.eco(terra=terrain.wrapper(6,TRUE),10,repduc=c(.4, .6),
#'    survive=c(.58,.65))
#' @name plant.arr
#' @rdname plant.arr
#'
#' @export
initiate.plants<-function(repduc, survive, names=NULL){
  if(is.null(names))
    names <- letters[seq_along(repduc)]
    # store the letters of the vector length of the value 'repduc'
  if(length(repduc) != length(survive))
    stop("Reproduction and survival parameters needed for all species")
    # stop the fxn and return error if the length of the two arguments
    #are not equivalent.
  repduc <- setNames(repduc, names)
    # set the values of repduc to the corresponding logical value of names.
  survive<- setNames(survive,names)
    # set the values of repduc to the corresponding logical value of names.

  return(list(repduc=repduc, survive=survive, names=names))
}


#' @param cell argument used to determine the given content of a matrix
#'    cell.
#' @param info A \code{\link{run.eco}} object
#' @rdname plant.arr
#' @export
survive <- function(cell, info){
  if(is.na(cell)==TRUE){
    cell<-NA
  }else{
    if(cell==''){
      for(i in sample(length(info$survive))){
      if(runif(1) <= info$survive[i]){
      cell<-names(info$survive[i])
  }else{
      cell<-''
    }
      }
    }
  }
  return(cell)
}
#' @param plants argument to call the 'plants' array in order to be
#'    manipulated.
#' @return the alterations done by plant.timestep
#' @rdname plant.arr
#' @export
plant.timestep <- function(plants, info){
  for(i in 1:ncol(plants)){
    for(j in 1:nrow(plants)){
      plants[j,i]<-survive(plants[j,i], info)
    }
  }
  return(plants)
}
#' @param terra terrain matrix generated by terrain.r
#' @param timesteps amount of 'timesteps' being applied. Gives the
#'    third dimension of the plants array.
#' @return plants array with simulated species inserted.
#' @rdname plant.arr
#' @export
run.eco<-function(terra, timesteps, repduc, survive){
  repduc<-repduc
  survive<-survive
  info<-initiate.plants(repduc,survive)
  plants <- array("", dim=c(dim(terra),timesteps+1))
  for(i in seq_len(dim(plants)[3]))
    plants[,,i][is.na(terra)] <- NA
  for(k in (seq_len(dim(plants)[3]-1)))
    plants[,,k] <- plant.timestep(plants[,,k], info)
  k<-k+1
  return(plants)
}
